### ISSUE TITLE
Problem with small resolution images getting cut off in mediabox cards

### ISSUE THREAD

**Issue by oliveratgithub** [zitrusfrisch/HTML-StarterKit#4]
Hi there,
thanks for the sweet & simple HTML Starter Kit!

I adapted it on a small website and so far it works pretty well, but I am facing an issue with images using the mediabox classes from the Demo site: when images are not longer in width but in height, and overall in a small resolution, they will be cut off - or I'll have to make them over 2 rows taking up way too much space on the site. See attached screenshots for an example.

![zitrusfrisch html-starter-kit small res images - example code inspection](https://cloud.githubusercontent.com/assets/280207/18631563/ff8c5a36-7e72-11e6-9679-9e8a1e8d7c6c.png)
![zitrusfrisch html-starter-kit small res images - example preview](https://cloud.githubusercontent.com/assets/280207/18631564/ffad8ee0-7e72-11e6-8bcd-00feed41cd4f.png)

Additionally I had to fix the card-figure margin (`figure,audio,video{margin:10px}`) in the CSS in order to make each Card better visible next to each other. I'll push a commit for this fix that you may review.

Is there a built-in way to fix this? Probably I am just doing something wrong? Otherwise I'd be happy to hear about how to work around this issue somehow.

Thanks,
Oliver

**Comment by zitrusfrisch** [comment]
Hey Oliver,

thanks for your message! Regarding your issues:

**Images getting cut off**
Apart from the `.mediabox` class you need to apply one of the [modifier classes](https://github.com/zitrusfrisch/HTML-StarterKit/blob/master/scss/components/_media.scss#L18), e.g. `.mediabox--2-1` or `.mediabox--square`, according to the aspect ratio of your image. Currently HTML-StarterKit only supports landscape or square formats, portrait formats might come with a future update. In general images scale up to their original size (`max-width: 100%;`) to avoid blurry results, so make sure they are big enough.

**Vertical spacing of cards / components in general**
Good point, since probably no one uses the card component without `margin-bottom`. If you want to add vertical spacing I recommend to use one of the [spacing variables](https://github.com/zitrusfrisch/HTML-StarterKit/blob/master/scss/core/_settings.scss#L9) though, e.g. `margin-bottom: $spacing-m`. They are based on the `$base-size` and ensure a consistent usage of spacings.

I hope that answers your questions?!

Cheers
Daniel
